# Generated by Django 4.0.2 on 2022-06-14 18:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
